<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AlertesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('alertes')->delete();
        
        \DB::table('alertes')->insert(array (
            0 => 
            array (
                'id' => 1001,
                'nom' => 'hétérogénéité marquée de l\'état coporel des vaches',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 1,
            ),
            1 => 
            array (
                'id' => 1002,
                'nom' => 'Etat de propreté du troupeau en hiver',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 1,
            ),
            2 => 
            array (
                'id' => 1003,
                'nom' => 'Comportements agressifs entre les vaches',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 1,
            ),
            3 => 
            array (
                'id' => 1004,
                'nom' => 'Pourcentage de vaches avec blessures',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 15,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 1,
            ),
            4 => 
            array (
                'id' => 1005,
                'nom' => 'Pourcentage d\'animaux accidentés au pâturage',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 1,
            ),
            5 => 
            array (
                'id' => 1006,
                'nom' => 'Pourcentage d\'animaux accidentés en stabulation',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 3,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 1,
            ),
            6 => 
            array (
                'id' => 1007,
            'nom' => 'Taux de mortalité des animaux d\'élevage (génisses après sevrage et vaches)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 1,
            ),
            7 => 
            array (
                'id' => 1008,
                'nom' => 'Taux de mortalités des animaux adultes en période d\'engraissement',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 1,
            ),
            8 => 
            array (
                'id' => 1009,
                'nom' => 'Taux d\'animaux de plus de 10 ans',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 15,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 1,
            ),
            9 => 
            array (
                'id' => 1010,
            'nom' => 'Montant des frais vétérinaires / vélage (hors conseil)',
                'type' => 'valeur',
                'unite' => '€',
                'niveau' => 100,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 1,
            ),
            10 => 
            array (
                'id' => 1011,
                'nom' => 'Poids des génisses à la reproduction',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 1,
            ),
            11 => 
            array (
                'id' => 1012,
                'nom' => 'Variation d\'état corporel en phase de reproduction',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 1,
            ),
            12 => 
            array (
                'id' => 1013,
            'nom' => 'Taux de gestation (nb de vaches pleines / nb de vaches mises à la reproduction)',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 1,
            ),
            13 => 
            array (
                'id' => 1014,
                'nom' => 'Nombre d\'avortements pendant les 3 derniers mois de gestation',
                'type' => 'valeur',
            'unite' => 'avortement(s)',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 1,
            ),
            14 => 
            array (
                'id' => 1015,
                'nom' => 'Intervalle vêlage 1 - vêlage 2',
                'type' => 'valeur',
                'unite' => 'jours',
                'niveau' => 390,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 1,
            ),
            15 => 
            array (
                'id' => 1016,
            'nom' => '% de vêlages difficiles des génisses (> 3 avec aide méca)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 20,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 1,
            ),
            16 => 
            array (
                'id' => 1017,
            'nom' => '% de vaches avec un problème post-vélage (matrice non-délivrance ou métrite)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 1,
            ),
            17 => 
            array (
                'id' => 1018,
                'nom' => 'Poids de naissance des veaux mâles',
                'type' => 'liste',
            'unite' => '(par rapport à la moyenne raciale)',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 1,
            ),
            18 => 
            array (
                'id' => 1019,
                'nom' => 'Engraissement : nombre d\'animaux en acidose clinique',
                'type' => 'valeur',
                'unite' => 'animaux',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 1,
            ),
            19 => 
            array (
                'id' => 1020,
                'nom' => 'Engraissement : nombre de morts',
                'type' => 'valeur',
                'unite' => 'animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 1,
            ),
            20 => 
            array (
                'id' => 1021,
                'nom' => 'Vaches : Diarrhées et aspect des bouses',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 1,
            ),
            21 => 
            array (
                'id' => 1022,
                'nom' => 'Vaches : cas cliniques de météorisation',
                'type' => 'valeur',
                'unite' => 'cas',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 1,
            ),
            22 => 
            array (
                'id' => 1023,
                'nom' => 'Vaches : cas de tétanie d\'herbage',
                'type' => 'valeur',
                'unite' => 'cas',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 1,
            ),
            23 => 
            array (
                'id' => 1024,
                'nom' => 'Taux de mortalité 0 à 2 j',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 1,
            ),
            24 => 
            array (
                'id' => 1025,
                'nom' => 'Taux de mortalité 3 à 15 j',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 3,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 1,
            ),
            25 => 
            array (
                'id' => 1026,
                'nom' => 'Taux de mortalité 15 j au sevrage',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 1,
            ),
            26 => 
            array (
                'id' => 1027,
                'nom' => 'GMQ 0-210 j',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 1,
            ),
            27 => 
            array (
                'id' => 1028,
                'nom' => '% veaux avec gros nombril',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 1,
            ),
            28 => 
            array (
                'id' => 1029,
                'nom' => '% de veaux avec problème digestif',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 1,
            ),
            29 => 
            array (
                'id' => 1030,
                'nom' => '% problème respiratoire',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 1,
            ),
            30 => 
            array (
                'id' => 1031,
            'nom' => '% problème fonctionnel (fractures écrasement etc.)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 3,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 1,
            ),
            31 => 
            array (
                'id' => 1032,
            'nom' => 'Prise de colostrum (% après 6 h)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 1,
            ),
            32 => 
            array (
                'id' => 1033,
                'nom' => '% colostrum ne venant pas de la mère',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 1,
            ),
            33 => 
            array (
                'id' => 1034,
                'nom' => 'perte de poids et perte d\'état',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            34 => 
            array (
                'id' => 1035,
                'nom' => 'Présence de poils piqués, robe déstructurée',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            35 => 
            array (
                'id' => 1036,
                'nom' => 'Nombre de traitements curatifs contre les strongles digestifs pour les vaches allaitantes',
                'type' => 'valeur',
                'unite' => 'nombre de traitements',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            36 => 
            array (
                'id' => 1037,
                'nom' => 'Nombre de traitements curatifs contre les strongles digestifs pour les génisses',
                'type' => 'valeur',
                'unite' => 'nombre de traitements',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            37 => 
            array (
                'id' => 1038,
                'nom' => 'Nombre de traitements curatifs contre les stronges respiratoires chez les génisses',
                'type' => 'valeur',
                'unite' => 'nombre de traitements',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            38 => 
            array (
                'id' => 1039,
                'nom' => 'Nombre de traitements curatifs contre les stronges respiratoires chez les vaches allaitantes',
                'type' => 'valeur',
                'unite' => 'nombre de traitements',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            39 => 
            array (
                'id' => 1040,
                'nom' => '% de bronchites vermineuses',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            40 => 
            array (
                'id' => 1041,
                'nom' => 'Douve : nombre de cas cliniques',
                'type' => 'valeur',
                'unite' => 'nombre de cas',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            41 => 
            array (
                'id' => 1042,
                'nom' => 'Grande douve et paramphistomes : nombre de traitements curatifs',
                'type' => 'valeur',
                'unite' => 'nombre de traitements',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            42 => 
            array (
                'id' => 1043,
                'nom' => 'Nombre de ticket d\'abattage avec la mention "foie saisi"',
                'type' => 'valeur',
                'unite' => 'nombre',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            43 => 
            array (
                'id' => 1044,
            'nom' => 'Traitements curatifs ectoparasites au pâturage (tiques, mouches …)',
                'type' => 'valeur',
                'unite' => 'nombre de traitements',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            44 => 
            array (
                'id' => 1045,
            'nom' => 'Traitements curatifs ectoparasites en stabulation (poux, gales, teignes, …)',
                'type' => 'valeur',
                'unite' => 'nombre de traitements',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 1,
            ),
            45 => 
            array (
                'id' => 1046,
            'nom' => '% de vaches avec mamelle défectueuse (déséquilibrée, 3 quartiers, trayons à problèmes)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 1,
            ),
            46 => 
            array (
                'id' => 1047,
                'nom' => 'Présence de cas de mammites',
                'type' => 'valeur',
                'unite' => 'nombre de mammites',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 1,
            ),
            47 => 
            array (
                'id' => 1048,
                'nom' => '% de vaches ayant boité sévèrement',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 7,
                'espece_id' => 1,
            ),
            48 => 
            array (
                'id' => 1049,
                'nom' => 'Nombre de taureau qui boite',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 7,
                'espece_id' => 1,
            ),
            49 => 
            array (
                'id' => 1050,
                'nom' => '% d\'animaux traités pour boiteries',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => '',
                'theme_id' => 7,
                'espece_id' => 1,
            ),
            50 => 
            array (
                'id' => 2000,
                'nom' => 'Hétérogénéité marquée de l\'état corporel des vaches intra-lot',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 2,
            ),
            51 => 
            array (
                'id' => 2001,
                'nom' => 'Animaux avec note d’état corporel inférieur ou égale à 2',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 2,
            ),
            52 => 
            array (
                'id' => 2002,
                'nom' => 'Animaux en fin de période de tarissement avec note d’état corporel inférieur à 3',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 2,
            ),
            53 => 
            array (
                'id' => 2003,
                'nom' => '% d’animaux avec robe déstructurée',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 25,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 2,
            ),
            54 => 
            array (
                'id' => 2004,
                'nom' => 'Etat de propreté des animaux en bâtiment',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 2,
            ),
            55 => 
            array (
                'id' => 2005,
                'nom' => 'Comportements agressifs entre elles',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 2,
            ),
            56 => 
            array (
                'id' => 2006,
            'nom' => '% d’animaux avec des blessures (gonflements, plaies, coups de corne, ...)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 15,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 2,
            ),
            57 => 
            array (
                'id' => 2007,
            'nom' => '% de mortalité des jeunes (de la naissance à l’âge du vêlage)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => 'OBS',
                'theme_id' => 1,
                'espece_id' => 2,
            ),
            58 => 
            array (
                'id' => 2008,
                'nom' => '% de mortalité des vaches',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 2,
                'modalite' => 'OBS',
                'theme_id' => 1,
                'espece_id' => 2,
            ),
            59 => 
            array (
                'id' => 2009,
                'nom' => '% de renouvellement du troupeau',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => 'OBS',
                'theme_id' => 1,
                'espece_id' => 2,
            ),
            60 => 
            array (
                'id' => 2010,
            'nom' => 'Montant des frais vétérinaires / vache présente (hors conseil)',
                'type' => 'valeur',
                'unite' => 'euros',
                'niveau' => 80,
                'modalite' => 'OBS',
                'theme_id' => 1,
                'espece_id' => 2,
            ),
            61 => 
            array (
                'id' => 2011,
                'nom' => 'Poids des génisses à la première insémination',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => 'OBS',
                'theme_id' => 2,
                'espece_id' => 2,
            ),
            62 => 
            array (
                'id' => 2012,
                'nom' => 'Age au premier vêlage',
                'type' => 'valeur',
                'unite' => 'mois',
                'niveau' => 36,
                'modalite' => 'OBS',
                'theme_id' => 2,
                'espece_id' => 2,
            ),
            63 => 
            array (
                'id' => 2013,
            'nom' => 'Intervalle vêlage-1ère insémination (vaches inséminées pendant les 3 derniers mois)',
                'type' => 'valeur',
                'unite' => 'jours',
                'niveau' => 82,
                'modalite' => 'OBS',
                'theme_id' => 2,
                'espece_id' => 2,
            ),
            64 => 
            array (
                'id' => 2014,
                'nom' => '% de vaches avec 3 inséminations ou plus',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 20,
                'modalite' => 'OBS',
                'theme_id' => 2,
                'espece_id' => 2,
            ),
            65 => 
            array (
                'id' => 2015,
                'nom' => '% de ré-insémination dans les 60 jours suivant une insémination',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 35,
                'modalite' => 'OBS',
                'theme_id' => 2,
                'espece_id' => 2,
            ),
            66 => 
            array (
                'id' => 2016,
            'nom' => 'IVV moyen du troupeau (hors lactation longues choisies)',
                'type' => 'valeur',
                'unite' => 'jours',
                'niveau' => 400,
                'modalite' => 'OBS',
                'theme_id' => 2,
                'espece_id' => 2,
            ),
            67 => 
            array (
                'id' => 2017,
                'nom' => '% de vaches avec un problème de non-délivrance après vêlage',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => 'OBS',
                'theme_id' => 2,
                'espece_id' => 2,
            ),
            68 => 
            array (
                'id' => 2018,
                'nom' => '% de vêlages difficiles des génisses',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 20,
                'modalite' => 'OBS',
                'theme_id' => 2,
                'espece_id' => 2,
            ),
            69 => 
            array (
                'id' => 2019,
                'nom' => '% de vaches avec une infection utérine après vêlage',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => 'OBS',
                'theme_id' => 2,
                'espece_id' => 2,
            ),
            70 => 
            array (
                'id' => 2020,
                'nom' => '% d\'avortements pendant les 3 derniers mois. ',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 1,
                'modalite' => 'OBS',
                'theme_id' => 2,
                'espece_id' => 2,
            ),
            71 => 
            array (
                'id' => 2021,
                'nom' => 'Cas clinique de fièvre de lait',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 0,
                'modalite' => 'OBS',
                'theme_id' => 3,
                'espece_id' => 2,
            ),
            72 => 
            array (
                'id' => 2022,
                'nom' => 'Cas de déplacement de caillette',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 0,
                'modalite' => 'OBS',
                'theme_id' => 3,
                'espece_id' => 2,
            ),
            73 => 
            array (
                'id' => 2023,
                'nom' => 'Cas de cétose',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 0,
                'modalite' => 'OBS',
                'theme_id' => 3,
                'espece_id' => 2,
            ),
            74 => 
            array (
                'id' => 2024,
            'nom' => '% de vaches avec TBi >45 g/kg et TPi < 28 ou 30g/kg ( ! particularités raciales)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 20,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 2,
            ),
            75 => 
            array (
                'id' => 2025,
                'nom' => 'Cas clinique de tétanie d\'herbage',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 0,
                'modalite' => 'OBS',
                'theme_id' => 3,
                'espece_id' => 2,
            ),
            76 => 
            array (
                'id' => 2026,
                'nom' => '% de vaches avec TBi – TPi < 3g/kg et TBi faible <35g/kg',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 15,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 2,
            ),
            77 => 
            array (
                'id' => 2027,
            'nom' => 'Pourcentage de vaches avec bouses anormales (liquides, mousse, claires)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 25,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 2,
            ),
            78 => 
            array (
                'id' => 2029,
                'nom' => 'Taux d’urée du lait du troupeau',
                'type' => 'valeur',
                'unite' => 'mg/l',
                'niveau' => 400,
                'modalite' => 'OBS',
                'theme_id' => 3,
                'espece_id' => 2,
            ),
            79 => 
            array (
                'id' => 2030,
            'nom' => 'Concentration en Cellules Somatiques du lait de Tank (CCSt) hors lait trié',
                'type' => 'valeur',
                'unite' => 'Cellules / ml',
                'niveau' => 250000,
                'modalite' => 'OBS',
                'theme_id' => 6,
                'espece_id' => 2,
            ),
            80 => 
            array (
                'id' => 2031,
                'nom' => 'Fréquence annuelle de mammites cliniques élevée',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 20,
                'modalite' => 'OBS',
                'theme_id' => 6,
                'espece_id' => 2,
            ),
            81 => 
            array (
                'id' => 2032,
                'nom' => '% nouvelles infections en période sèche',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => 'OBS',
                'theme_id' => 6,
                'espece_id' => 2,
            ),
            82 => 
            array (
                'id' => 2033,
                'nom' => '% d\'infections mammaires en début de lactation sur les primipares',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => 'OBS',
                'theme_id' => 6,
                'espece_id' => 2,
            ),
            83 => 
            array (
                'id' => 2034,
                'nom' => 'Présence de staphylocoques dans le lait',
                'type' => 'valeur',
                'unite' => 'nombre de cas',
                'niveau' => 0,
                'modalite' => 'OBS',
                'theme_id' => 6,
                'espece_id' => 2,
            ),
            84 => 
            array (
                'id' => 2035,
                'nom' => '% de mortalité durant les premières 24h ',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 2,
            ),
            85 => 
            array (
                'id' => 2036,
                'nom' => '% de mortalité de 1 jour de vie jusqu\'au sevrage ',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 2,
            ),
            86 => 
            array (
                'id' => 2037,
            'nom' => '% de morbidité total (% de veaux traités, en retard, parmi les veaux élevés)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 2,
            ),
            87 => 
            array (
                'id' => 2038,
                'nom' => '% veaux avec gros nombril',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 2,
            ),
            88 => 
            array (
                'id' => 2039,
            'nom' => '% de veaux avec problème digestif (diarrhées, coccidioses)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 2,
            ),
            89 => 
            array (
                'id' => 2040,
                'nom' => '% de veaux avec problèmes respiratoires',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 2,
            ),
            90 => 
            array (
                'id' => 2041,
                'nom' => 'Baisse de la production laitière',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            91 => 
            array (
                'id' => 2042,
                'nom' => 'Hétérogénéité de croissance sur les jeunes après 8 mois d’âge',
                'type' => 'valeur',
                'unite' => 'g/jour',
                'niveau' => 500,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            92 => 
            array (
                'id' => 2043,
                'nom' => 'Etat corporel hétérogène',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            93 => 
            array (
                'id' => 2044,
                'nom' => 'Pas de reprise d\'état en fin de lactation',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            94 => 
            array (
                'id' => 2045,
                'nom' => '% de diarrhées sur jeunes et adultes',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 25,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            95 => 
            array (
                'id' => 2046,
                'nom' => 'Poils piqués et ternes, robe déstructurée',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            96 => 
            array (
                'id' => 2047,
                'nom' => 'Toux estivale ou automnale',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            97 => 
            array (
                'id' => 2048,
                'nom' => 'Essoufflement lors de l’effort',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            98 => 
            array (
                'id' => 2049,
                'nom' => 'Durée de pâturage cumulé avant premier vêlage',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            99 => 
            array (
                'id' => 2050,
            'nom' => 'Œdème sous glossien (signe de la bouteille)',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            100 => 
            array (
                'id' => 2051,
                'nom' => 'Ticket d’abattage avec la mention « foie saisie »',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            101 => 
            array (
                'id' => 2052,
                'nom' => 'Vaches maigres à poils piqués ',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            102 => 
            array (
                'id' => 2053,
            'nom' => 'Diarrhées sur les animaux adultes (hors causes alimentaires)',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            103 => 
            array (
                'id' => 2054,
                'nom' => 'Zones de dépilation, de grattage ? ',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 2,
            ),
            104 => 
            array (
                'id' => 2055,
                'nom' => '% de vaches boitant sévèrement selon le score de locomotion',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 7,
                'espece_id' => 2,
            ),
            105 => 
            array (
                'id' => 2056,
                'nom' => 'Réformes pour problèmes de pattes',
                'type' => 'valeur',
                'unite' => 'nombre d’animaux',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 7,
                'espece_id' => 2,
            ),
            106 => 
            array (
                'id' => 2057,
                'nom' => '% d\'animaux traités pour boiteries',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 15,
                'modalite' => '',
                'theme_id' => 7,
                'espece_id' => 2,
            ),
            107 => 
            array (
                'id' => 2058,
                'nom' => '% de vaches avec des sabots allongés dans le troupeau',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => '',
                'theme_id' => 7,
                'espece_id' => 2,
            ),
            108 => 
            array (
                'id' => 2059,
                'nom' => 'Présence de salmonelles dans le lait',
                'type' => 'valeur',
                'unite' => 'nombre de cas',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 2,
            ),
            109 => 
            array (
                'id' => 2060,
                'nom' => 'Présence de listeria dans le lait',
                'type' => 'valeur',
                'unite' => 'nombre de cas',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 2,
            ),
            110 => 
            array (
                'id' => 2061,
                'nom' => 'Présence de colibacilles dans le lait',
                'type' => 'valeur',
                'unite' => 'nombre de cas',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 2,
            ),
            111 => 
            array (
                'id' => 3000,
                'nom' => 'État corporel du lot ou du troupeau',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 3,
            ),
            112 => 
            array (
                'id' => 3001,
                'nom' => 'État de propreté des animaux',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 3,
            ),
            113 => 
            array (
                'id' => 3002,
                'nom' => 'Taux de réforme',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 30,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 3,
            ),
            114 => 
            array (
                'id' => 3003,
                'nom' => 'Taux de mortalité des chèvres',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 3,
            ),
            115 => 
            array (
                'id' => 3004,
                'nom' => '% de chèvres atteintes de troubles respiratoires',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 3,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 3,
            ),
            116 => 
            array (
                'id' => 3005,
                'nom' => '% de chèvres atteintes de troubles digestifs ?',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 3,
            ),
            117 => 
            array (
                'id' => 3006,
            'nom' => 'Poids moyen du lot à 8 mois (par rapport au poids moyen adulte)',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 3,
            ),
            118 => 
            array (
                'id' => 3007,
                'nom' => '% d\'animaux à comportements sociaux anormaux',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 3,
            ),
            119 => 
            array (
                'id' => 3008,
                'nom' => '% d\'animaux présentant des troubles nerveux',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 3,
            ),
            120 => 
            array (
                'id' => 3009,
                'nom' => 'Poids chevrettes à la première mise à la reproduction',
                'type' => 'valeur',
                'unite' => 'kg',
                'niveau' => 35,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 3,
            ),
            121 => 
            array (
                'id' => 3010,
                'nom' => 'Pourcentage de chèvres ayant mis-bas en 2 mois',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 3,
            ),
            122 => 
            array (
                'id' => 3011,
                'nom' => 'Non-délivrance après mise bas',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 3,
            ),
            123 => 
            array (
                'id' => 3012,
                'nom' => 'Pourcentage de mises bas difficiles',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 3,
            ),
            124 => 
            array (
                'id' => 3013,
            'nom' => 'Avortements (+ de 3 en 1 semaine ou + de 4 % au total)',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 3,
            ),
            125 => 
            array (
                'id' => 3014,
                'nom' => 'Entérotoxémies',
                'type' => 'valeur',
                'unite' => 'animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 3,
            ),
            126 => 
            array (
                'id' => 3015,
                'nom' => 'Toxémies de gestation, cétose',
                'type' => 'valeur',
                'unite' => 'animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 3,
            ),
            127 => 
            array (
                'id' => 3016,
                'nom' => 'Acidose ruminale',
                'type' => 'valeur',
                'unite' => 'animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 3,
            ),
            128 => 
            array (
                'id' => 3017,
                'nom' => 'Alcalose',
                'type' => 'valeur',
                'unite' => 'animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 3,
            ),
            129 => 
            array (
                'id' => 3018,
            'nom' => 'Urolithiase (gravelle) du bouc',
                'type' => 'valeur',
                'unite' => 'animaux',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 3,
                'espece_id' => 3,
            ),
            130 => 
            array (
                'id' => 3019,
            'nom' => 'Concentration en Cellules Somatiques du lait de Tank (CCSt)',
                'type' => 'valeur',
                'unite' => 'cellules',
                'niveau' => 3000000,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 3,
            ),
            131 => 
            array (
                'id' => 3020,
                'nom' => 'Si transformation : présence de salmonelles',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 3,
            ),
            132 => 
            array (
                'id' => 3021,
                'nom' => 'Si transformation : présence de listeria',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 3,
            ),
            133 => 
            array (
                'id' => 3022,
                'nom' => 'Si transformation : présence de staphylocoques > seuil réglemen.',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 3,
            ),
            134 => 
            array (
                'id' => 3023,
                'nom' => 'Pourcentage de chèvres infectées incurables',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 3,
            ),
            135 => 
            array (
                'id' => 3024,
            'nom' => 'Pourcentage de chèvres avec déséquilibres mammaires importants (largeur 3 doigts)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 30,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 3,
            ),
            136 => 
            array (
                'id' => 3025,
                'nom' => 'Pourcentage de cas de mammites cliniques pendant le 1er mois',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 3,
            ),
            137 => 
            array (
                'id' => 3026,
                'nom' => 'Pourcentage de chèvres avec abcès',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 3,
            ),
            138 => 
            array (
                'id' => 3027,
            'nom' => 'Taux de mortalité durant les premières 24h (hors avortement)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 3,
            ),
            139 => 
            array (
                'id' => 3028,
                'nom' => 'Renouvellement : Taux de mortalité chez les chevrettes',
                'type' => 'valeur',
                'unite' => 'nombre',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 3,
            ),
            140 => 
            array (
                'id' => 3029,
                'nom' => 'Taux de mortalité avant sevrage',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 3,
            ),
            141 => 
            array (
                'id' => 3030,
                'nom' => 'diarrhées néonatales les 2 premières semaines',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 15,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 3,
            ),
            142 => 
            array (
                'id' => 3031,
                'nom' => 'infection du nombril',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 3,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 3,
            ),
            143 => 
            array (
                'id' => 3032,
                'nom' => 'Nombre de cas d\'arthrite',
                'type' => 'valeur',
                'unite' => 'animaux',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 3,
            ),
            144 => 
            array (
                'id' => 3033,
                'nom' => 'problèmes respiratoires',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 3,
            ),
            145 => 
            array (
                'id' => 3034,
                'nom' => 'Poids des chevrettes au sevrage',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 3,
            ),
            146 => 
            array (
                'id' => 3035,
                'nom' => 'Age des 
chevrettes au sevrage',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 3,
            ),
            147 => 
            array (
                'id' => 3036,
                'nom' => 'Cryptosporidiose',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 3,
            ),
            148 => 
            array (
                'id' => 3037,
                'nom' => 'Coccidiose',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 3,
            ),
            149 => 
            array (
                'id' => 3038,
                'nom' => 'Résultats de coproscopies',
                'type' => 'valeur',
                'unite' => 'opg',
                'niveau' => 800,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 3,
            ),
            150 => 
            array (
                'id' => 3039,
                'nom' => 'Strongles gastro-intestinaux : symptômes',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 3,
            ),
            151 => 
            array (
                'id' => 3040,
                'nom' => 'Strongles respiratoires : symptômes',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 3,
            ),
            152 => 
            array (
                'id' => 3041,
                'nom' => 'Traitement systématique contre les strongles digestifs',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 3,
            ),
            153 => 
            array (
                'id' => 3042,
                'nom' => 'Échec fréquent des traitements',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 3,
            ),
            154 => 
            array (
                'id' => 3043,
                'nom' => '% de chèvres avec muqueuses pales',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 25,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 3,
            ),
            155 => 
            array (
                'id' => 3044,
                'nom' => 'Présence de paramphistomes à l\'autopsie',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 3,
            ),
            156 => 
            array (
                'id' => 3045,
            'nom' => 'Traitements ectoparasites au pâturage (tiques, mouches ...) ',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 3,
            ),
            157 => 
            array (
                'id' => 3046,
            'nom' => 'Traitements ectoparasites en stabulation (poux, gales, teignes,puce …)',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 3,
            ),
            158 => 
            array (
                'id' => 3047,
            'nom' => 'Onglons déformés ou sabots allongés (ski) fréquents',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 7,
                'espece_id' => 3,
            ),
            159 => 
            array (
                'id' => 3048,
            'nom' => 'Présence d\'arthrites / gros genoux (chèvres)',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 7,
                'espece_id' => 3,
            ),
            160 => 
            array (
                'id' => 3049,
                'nom' => 'Si transformation : présence d’Escherichia coli',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 3,
            ),
            161 => 
            array (
                'id' => 3050,
            'nom' => 'Présence de lésions cutanées (ectoparasites)',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 3,
            ),
            162 => 
            array (
                'id' => 3051,
            'nom' => 'Présence de kératites (mouches)',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 5,
                'espece_id' => 3,
            ),
            163 => 
            array (
                'id' => 4000,
                'nom' => 'Homogénéité et état corporel du lot ou du troupeau',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 4,
            ),
            164 => 
            array (
                'id' => 4001,
                'nom' => 'Etat de propreté des animaux',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 4,
            ),
            165 => 
            array (
                'id' => 4002,
                'nom' => 'Taux de réforme',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 30,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 4,
            ),
            166 => 
            array (
                'id' => 4003,
                'nom' => 'Taux de mortalité des brebis',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 4,
            ),
            167 => 
            array (
                'id' => 4004,
                'nom' => '% de brebis atteintes de troubles respiratoires chroniques',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 3,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 4,
            ),
            168 => 
            array (
                'id' => 4005,
            'nom' => '% de brebis atteintes de troubles digestifs ? (propreté arrière train, diarrhée, ballonnement, etc..)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 4,
            ),
            169 => 
            array (
                'id' => 4006,
                'nom' => 'Poids moyen du lot à 8 mois',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 4,
            ),
            170 => 
            array (
                'id' => 4007,
            'nom' => '% d\'animaux à comportements sociaux anormaux ou stéréotypies (peur, tics, pica, …)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 4,
            ),
            171 => 
            array (
                'id' => 4008,
            'nom' => '% d\'animaux présentant des troubles nerveux (convulsion, pousser au mur, perte d’équilibre, coma, …)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 1,
                'espece_id' => 4,
            ),
            172 => 
            array (
                'id' => 4009,
                'nom' => 'Taux d\'infertilité des antenaises et agnelles : vides / mises à la reproduction',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 15,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 4,
            ),
            173 => 
            array (
                'id' => 4010,
                'nom' => '% de mises-bas en 1 mois',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 4,
            ),
            174 => 
            array (
                'id' => 4011,
                'nom' => 'Taux d’infertilité en fonction de la période et de la durée de la lutte',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 10,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 4,
            ),
            175 => 
            array (
                'id' => 4012,
            'nom' => 'Taux d\'avortement tardif (dans les 15 jours avant la mise bas prévue) des brebis',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 4,
            ),
            176 => 
            array (
                'id' => 4013,
                'nom' => 'Taux d’avortement tardif des antenaises',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 4,
            ),
            177 => 
            array (
                'id' => 4014,
                'nom' => 'Y-a-t’il eu plus de 3 avortements en une semaine à la dernière mise-bas',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 0,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 4,
            ),
            178 => 
            array (
                'id' => 4015,
                'nom' => '% de brebis atteintes de toxémie de gestation',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 4,
            ),
            179 => 
            array (
                'id' => 4016,
                'nom' => '% de brebis atteintes de prolapsus vaginal en fin de gestation',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 3,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 4,
            ),
            180 => 
            array (
                'id' => 4017,
                'nom' => '% de brebis ayant eu un agnelage difficile',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 4,
            ),
            181 => 
            array (
                'id' => 4018,
                'nom' => 'Taux de prolificité',
                'type' => 'liste',
                'unite' => 'Par rapport à la moyenne raciale',
                'niveau' => 90,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 4,
            ),
            182 => 
            array (
                'id' => 4019,
                'nom' => 'Durée de mise bas d\'un lot',
                'type' => 'valeur',
                'unite' => 'mois',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 2,
                'espece_id' => 4,
            ),
            183 => 
            array (
                'id' => 4020,
                'nom' => '% de brebis réformées pour cause de mammite et/ou perte d\'un quartier',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 6,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 4,
            ),
            184 => 
            array (
                'id' => 4021,
                'nom' => '% de brebis ayant des lésions de la mamelle durant la phase d\'allaitement',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 6,
                'modalite' => '',
                'theme_id' => 6,
                'espece_id' => 4,
            ),
            185 => 
            array (
                'id' => 4022,
            'nom' => '% d\'agneaux de faible poids à la naissance (< 2kg)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 15,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            186 => 
            array (
                'id' => 4023,
            'nom' => 'Taux de mortalité (hors prédation) naissance-vente ',
                'type' => 'liste',
                'unite' => '',
                'niveau' => 1,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            187 => 
            array (
                'id' => 4024,
                'nom' => 'Taux de mortinatalité mort-né et dans les premières 48h',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            188 => 
            array (
                'id' => 4025,
            'nom' => 'Taux de mortalité de 48 heures à 10 jours (parmi les agneaux nés totaux)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 4,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            189 => 
            array (
                'id' => 4026,
            'nom' => 'Taux de mortalité de 10 jours au sevrage-commercialisation (parmi les agneaux nés totaux)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 3,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            190 => 
            array (
                'id' => 4027,
            'nom' => 'Taux de mortalité (hors prédation) entre le sevrage et la première mise bas des agnelles',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 3,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            191 => 
            array (
                'id' => 4028,
                'nom' => '% d\'agneaux n\'ayant pas tété 2h après la naissance ',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            192 => 
            array (
                'id' => 4029,
                'nom' => '% d’agneaux faibles qui ne se lèvent pas au bout de 20 minutes environs',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            193 => 
            array (
                'id' => 4030,
            'nom' => '% d\'agneaux atteints de "agneau baveur" (0-5 jours)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 3,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            194 => 
            array (
                'id' => 4031,
            'nom' => '% d\'agneaux atteints de troubles du cordon (gros cordon, nombril humide)',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 2,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            195 => 
            array (
                'id' => 4032,
                'nom' => '% d\'agneaux atteints d\'ecthyma sévère',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 5,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            196 => 
            array (
                'id' => 4033,
                'nom' => '% d\'agneaux atteints de diarrhée avant 3 semaines',
                'type' => 'pourcentage',
                'unite' => '%',
                'niveau' => 3,
                'modalite' => '',
                'theme_id' => 4,
                'espece_id' => 4,
            ),
            197 => 
            array (
                'id' => 4035,
            'nom' => '% d\'agneaux atteints de diarrhée de 3 semaines au sevrage)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 4,
        ),
        198 => 
        array (
            'id' => 4036,
            'nom' => '% d\'agneaux atteints de diarrhée après sevrage en bergerie',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 4,
        ),
        199 => 
        array (
            'id' => 4037,
            'nom' => '% d\'agneaux atteints de diarrhée après sevrage à l’herbe',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 12,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 4,
        ),
        200 => 
        array (
            'id' => 4038,
            'nom' => '% d\'agneaux atteints de troubles respiratoires',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 4,
        ),
        201 => 
        array (
            'id' => 4039,
        'nom' => '% de saisie à l\'abattoir en lien avec des problèmes respiratoires (côtelette) pleurésie (si information disponible)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 4,
        ),
        202 => 
        array (
            'id' => 4040,
            'nom' => '% d\'agneaux atteints d\'arthrite',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 4,
        ),
        203 => 
        array (
            'id' => 4041,
            'nom' => '% d\'agneaux atteints de raide',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 4,
        ),
        204 => 
        array (
            'id' => 4042,
            'nom' => '% d\'agneaux atteints d\'entérotoxémie de 2 semaines à la vente',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 4,
        ),
        205 => 
        array (
            'id' => 4043,
            'nom' => '% d\'agneaux atteints de ballonnement / météorisation',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 2,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 4,
        ),
        206 => 
        array (
            'id' => 4044,
            'nom' => '% d\'agneaux atteints de troubles nerveux',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 2,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 4,
        ),
        207 => 
        array (
            'id' => 4045,
            'nom' => '% d\'agnelles atteintes de diarrhées au pâturage',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 10,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 4,
        ),
        208 => 
        array (
            'id' => 4046,
            'nom' => '% de brebis ayant des lésions de la peau dû à la gale',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 4,
        ),
        209 => 
        array (
            'id' => 4047,
        'nom' => '% de brebis ayant des lésions de la peau (hors gales...) et de la toison :',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 4,
        ),
        210 => 
        array (
            'id' => 4048,
        'nom' => 'Présence de brebis avec indice FAMACHA >3 (rose pâle, blanc)',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 4,
        ),
        211 => 
        array (
            'id' => 4049,
        'nom' => 'Signes d’infestation par des parasites gastro-intestinaux (amaigrissement, anémie, copro > 1000, …)',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 4,
        ),
        212 => 
        array (
            'id' => 4050,
        'nom' => 'Signes d’infestation par la grande douve + paramphistome (symptômes, sérologie pour GD, copro pour P)',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 4,
        ),
        213 => 
        array (
            'id' => 4051,
            'nom' => 'Signes d’infestation par la petite douve',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 4,
        ),
        214 => 
        array (
            'id' => 4052,
            'nom' => 'Signes d’infestation par les strongles pulmonaires',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 4,
        ),
        215 => 
        array (
            'id' => 4053,
            'nom' => 'Myases - Oestres',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 4,
        ),
        216 => 
        array (
            'id' => 4054,
            'nom' => '% de brebis traitées individuellement pour boiteries',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 7,
            'espece_id' => 4,
        ),
        217 => 
        array (
            'id' => 4055,
            'nom' => 'Nombre de traitements collectifs /an',
            'type' => 'valeur',
            'unite' => 'traitements/lot',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 7,
            'espece_id' => 4,
        ),
        218 => 
        array (
            'id' => 4056,
            'nom' => '% de brebis boitant sévèrement',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 7,
            'espece_id' => 4,
        ),
        219 => 
        array (
            'id' => 4057,
        'nom' => 'Nombre d\'intervention curative sur les onglons (soins, parage curatif, pédiluve…)',
            'type' => 'valeur',
            'unite' => 'interventions',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 7,
            'espece_id' => 4,
        ),
        220 => 
        array (
            'id' => 5000,
            'nom' => 'Homogénéité et état corporel du lot ou du troupeau',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 1,
            'espece_id' => 5,
        ),
        221 => 
        array (
            'id' => 5001,
            'nom' => 'Etat de propreté des animaux ',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 1,
            'espece_id' => 5,
        ),
        222 => 
        array (
            'id' => 5002,
            'nom' => 'Taux de réforme ',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 30,
            'modalite' => '',
            'theme_id' => 1,
            'espece_id' => 5,
        ),
        223 => 
        array (
            'id' => 5003,
            'nom' => 'Taux de mortalité des brebis',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 1,
            'espece_id' => 5,
        ),
        224 => 
        array (
            'id' => 5004,
        'nom' => '% de brebis atteintes de troubles respiratoires (atteinte chronique ou épidémique)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 1,
            'espece_id' => 5,
        ),
        225 => 
        array (
            'id' => 5005,
        'nom' => '% de brebis atteintes de troubles digestifs ? (propreté arrière train, diarrhée, ballonnement, etc..)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 10,
            'modalite' => '',
            'theme_id' => 1,
            'espece_id' => 5,
        ),
        226 => 
        array (
            'id' => 5006,
            'nom' => 'Poids moyen du lot à 8 mois ',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 1,
            'espece_id' => 5,
        ),
        227 => 
        array (
            'id' => 5007,
            'nom' => '% d\'animaux à comportements sociaux anormaux ou stéréotypies',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 1,
            'espece_id' => 5,
        ),
        228 => 
        array (
            'id' => 5008,
        'nom' => '% d\'animaux présentant des troubles nerveux (hors biberon et sevrage)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 2,
            'modalite' => '',
            'theme_id' => 1,
            'espece_id' => 5,
        ),
        229 => 
        array (
            'id' => 5009,
        'nom' => 'Taux d\'infertilité des antenaises et agnelles : % vides / total en repro (sur 2 mois de lutte)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 15,
            'modalite' => '',
            'theme_id' => 2,
            'espece_id' => 5,
        ),
        230 => 
        array (
            'id' => 5011,
            'nom' => 'Taux d’infertilité en fonction de la période et de la durée de la lutte ',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 10,
            'modalite' => '',
            'theme_id' => 2,
            'espece_id' => 5,
        ),
        231 => 
        array (
            'id' => 5012,
        'nom' => 'Taux d\'avortement tardif adultes (dans les 15 jours avant la mise bas prévue)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 2,
            'modalite' => '',
            'theme_id' => 2,
            'espece_id' => 5,
        ),
        232 => 
        array (
            'id' => 5013,
        'nom' => 'Taux d\'avortement tardif agnelles (dans les 15 jours avant la mise bas prévue)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 2,
            'espece_id' => 5,
        ),
        233 => 
        array (
            'id' => 5014,
            'nom' => '% de brebis atteintes de toxémie de gestation',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 2,
            'espece_id' => 5,
        ),
        234 => 
        array (
            'id' => 5015,
            'nom' => '% de brebis atteintes de prolapsus vaginal en fin de gestation',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 2,
            'espece_id' => 5,
        ),
        235 => 
        array (
            'id' => 5016,
            'nom' => '% de brebis ayant eu un agnelage difficile',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 2,
            'espece_id' => 5,
        ),
        236 => 
        array (
            'id' => 5017,
            'nom' => 'Taux de prolificité',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 2,
            'espece_id' => 5,
        ),
        237 => 
        array (
            'id' => 5018,
            'nom' => 'Durée de mise bas d\'un lot',
            'type' => 'valeur',
            'unite' => 'mois',
            'niveau' => 2,
            'modalite' => '',
            'theme_id' => 2,
            'espece_id' => 5,
        ),
        238 => 
        array (
            'id' => 5019,
            'nom' => 'Mammites cliniques',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 6,
            'espece_id' => 5,
        ),
        239 => 
        array (
            'id' => 5020,
            'nom' => 'Mammites subcliniques, concentration cellulaire du tank',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 10,
            'modalite' => '',
            'theme_id' => 6,
            'espece_id' => 5,
        ),
        240 => 
        array (
            'id' => 5021,
            'nom' => 'Germes Listéria, salmonelle, E.coli et STEC',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 6,
            'espece_id' => 5,
        ),
        241 => 
        array (
            'id' => 5022,
            'nom' => 'Butyriques',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 6,
            'espece_id' => 5,
        ),
        242 => 
        array (
            'id' => 5023,
            'nom' => 'Pseudomonas',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 6,
            'espece_id' => 5,
        ),
        243 => 
        array (
            'id' => 5024,
        'nom' => '% d\'agneaux de faible poids à la naissance (< 2kg)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 15,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        244 => 
        array (
            'id' => 5025,
        'nom' => 'Taux de mortalité (hors prédation) naissance-vente (parmi les agneaux nés totaux)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 12,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        245 => 
        array (
            'id' => 5026,
            'nom' => 'Taux de mortinatalité mort-né et dans les premières 48h',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        246 => 
        array (
            'id' => 5027,
        'nom' => 'Taux de mortalité de 48 heures à 10 jours (parmi les agneaux nés totaux)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 4,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        247 => 
        array (
            'id' => 5028,
        'nom' => 'Taux de mortalité de 10 jours au sevrage-commercialisation (parmi les agneaux nés totaux)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        248 => 
        array (
            'id' => 5029,
        'nom' => 'Taux de mortalité (hors prédation) entre le sevrage et la première mise bas des agnelles',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        249 => 
        array (
            'id' => 5030,
        'nom' => '% d\'agneaux n\'ayant pas tété 2h après la naissance (faiblesse, bouche froide, dos rond, bêlement de l\'agneau, mamelle tendue, agneau creux...)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 2,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        250 => 
        array (
            'id' => 5031,
            'nom' => '% d’agneaux faibles qui ne se lèvent pas au bout de 20 minutes environs',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        251 => 
        array (
            'id' => 5032,
        'nom' => '% d\'agneaux atteints de "agneau baveur" (0-5 jours)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 2,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        252 => 
        array (
            'id' => 5033,
        'nom' => '% d\'agneaux atteints de troubles du cordon (gros cordon, nombril humide)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        253 => 
        array (
            'id' => 5034,
            'nom' => '% d\'agneaux atteints d\'ecthyma sévère',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 4,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        254 => 
        array (
            'id' => 5035,
            'nom' => '% d\'agneaux atteints de diarrhée avant 1 mois',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 4,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        255 => 
        array (
            'id' => 5037,
            'nom' => '% d\'agneaux atteints de diarrhée entre 1 mois et le sevrage',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        256 => 
        array (
            'id' => 5038,
        'nom' => '% d\'agneaux atteints de diarrhée (après sevrage) en bergerie',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        257 => 
        array (
            'id' => 5039,
        'nom' => '% d\'agneaux atteints de diarrhée (après sevrage) à l’herbe',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 12,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        258 => 
        array (
            'id' => 5040,
            'nom' => '% d\'agneaux atteints de troubles respiratoires',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        259 => 
        array (
            'id' => 5041,
        'nom' => '% de saisie à l\'abattoir en lien avec des problèmes respiratoires (côtelette) pleurésie (si information disponible)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        260 => 
        array (
            'id' => 5042,
            'nom' => '% d\'agneaux atteints d’arthrite',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        261 => 
        array (
            'id' => 5043,
            'nom' => '% d\'agneaux atteints de raide',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        262 => 
        array (
            'id' => 5044,
            'nom' => '% d\'agneaux atteints de troubles locomoteurs d’origine accidentelle',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 2,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        263 => 
        array (
            'id' => 5045,
            'nom' => '% d\'agneaux atteints d\'enterotoxémie de 2 semaines à la vente',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        264 => 
        array (
            'id' => 5046,
            'nom' => '% d\'agneaux atteints de ballonnement / météorisation',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 2,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        265 => 
        array (
            'id' => 5047,
            'nom' => '% d\'agneaux atteints de troubles nerveux',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 2,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        266 => 
        array (
            'id' => 5048,
            'nom' => '% d\'agnelles atteintes de diarrhées au pâturage',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 10,
            'modalite' => '',
            'theme_id' => 4,
            'espece_id' => 5,
        ),
        267 => 
        array (
            'id' => 5049,
            'nom' => '% de brebis ayant des lésions de la peau dû à la gale',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 0,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 5,
        ),
        268 => 
        array (
            'id' => 5050,
        'nom' => '% de brebis ayant des lésions de la peau (hors gales...) et de la toison : ',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 5,
        ),
        269 => 
        array (
            'id' => 5051,
        'nom' => '% de brebis avec indice FAMACHA >3 (rose pâle, blanc)',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 5,
        ),
        270 => 
        array (
            'id' => 5052,
            'nom' => 'Présence de parasitisme gastro-intestinal',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 5,
        ),
        271 => 
        array (
            'id' => 5053,
        'nom' => 'Présence de parasitisme par la Grande Douve (+ paramphistome)',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 5,
        ),
        272 => 
        array (
            'id' => 5054,
            'nom' => 'Présence de parasitisme par la Petite Douve',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 5,
        ),
        273 => 
        array (
            'id' => 5055,
            'nom' => 'Présence de parasitisme par les strongles pulmonaires',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 5,
        ),
        274 => 
        array (
            'id' => 5056,
            'nom' => 'Présence de Coccidiose',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 5,
        ),
        275 => 
        array (
            'id' => 5057,
            'nom' => 'Myases',
            'type' => 'liste',
            'unite' => '',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 5,
            'espece_id' => 5,
        ),
        276 => 
        array (
            'id' => 5059,
            'nom' => '% de brebis traitées individuellement pour boiteries ',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 7,
            'espece_id' => 5,
        ),
        277 => 
        array (
            'id' => 5060,
            'nom' => 'Nombre de traitements collectifs /an',
            'type' => 'valeur',
            'unite' => 'nombre de traitements',
            'niveau' => 3,
            'modalite' => '',
            'theme_id' => 7,
            'espece_id' => 5,
        ),
        278 => 
        array (
            'id' => 5061,
            'nom' => '% de brebis boitant sévèrement',
            'type' => 'pourcentage',
            'unite' => '%',
            'niveau' => 5,
            'modalite' => '',
            'theme_id' => 7,
            'espece_id' => 5,
        ),
        279 => 
        array (
            'id' => 5062,
        'nom' => 'Nombre d\'intervention curative sur les onglons (soins, parage curatif, pédiluve…) ',
            'type' => 'valeur',
            'unite' => 'nombre d’animaux',
            'niveau' => 1,
            'modalite' => '',
            'theme_id' => 7,
            'espece_id' => 5,
        ),
    ));
        
        
    }
}